version: '{build}'
skip_tags: true
clone_depth: 10
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - SET PATH=%JAVA_HOME%\bin;%PATH:C:\Ruby193\bin;=%
  - java -version
  - choco install maven
  - mvn --version
  - SET PATH=C:\bin\apache-maven-3.2.3\bin;%PATH%
  - echo %PATH%
build_script:
  - mvn clean package 
test_script:
  - mvn test
 artifacts:
  - path: C:\projects\titanic\target\*.jar
    name: Titanic
